OPEN-ENT-NG/support

- src/main/resources/i18n/fr.json
> minor change on key Student

- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/resources/public/js/controller.js
- src/main/resources/sql/021-support.sql
Hello David, je passe par une PR avant de pousser sur next, je pense qu'une petite relecture ne ferait pas de mal là-dessus.
De plus, je ne sais plus si on voulait déployer vraiment dès la 3.5 ou non.
> fix : #22976, fixed timezone problems

- src/main/resources/public/template/create-ticket.html
- src/main/resources/public/template/edit-ticket.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/view-src/support.html
Pop up "Les modifications que vous avez apportées ne seront peut-être pas enregistrées. Souhaitez vous quitter cette page?" quand on veut quitter un formulaire qu'on a modifié. 
Formulaires et champs concernés :
- création de ticket (sujet, description)
- modification de ticket (statut, établissement, catégorie, sujet, description, commentaire)
> feat(form): EV-145 add warning before cancel form

- src/main/resources/public/template/create-ticket.html
- src/main/resources/public/template/edit-ticket.html
- src/main/resources/public/template/view-bugtracker-issue.html
- src/main/resources/public/template/view-ticket.html
Using `ng-bind-html` to interpret other than http url (image path etc...)
> fix(form): #CO-466 add editor component to interpret http and extra char

- .github/workflows/dev-check-repository.yml
- build.gradle
- build.sh
- coverage/front/cobertura-coverage.xml
- gradle.properties
- jest.config.js
- package.json
- src/main/java/net/atos/entng/support/Support.java
- src/main/java/net/atos/entng/support/controllers/AttachmentController.java
- src/main/java/net/atos/entng/support/services/AttachmentService.java
- src/main/java/net/atos/entng/support/services/impl/AttachmentServiceSqlImpl.java
- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/_support.scss
- src/main/resources/public/sass/global/generic/_index.scss
- src/main/resources/public/sass/global/generic/_toasts.scss
- src/main/resources/public/template/attachment-delete-picture-lightbox.html
- src/main/resources/public/template/view-ticket.html
- src/main/resources/public/ts/app.ts
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/models/Attachment.ts
- src/main/resources/public/ts/services/__tests__/attachment.service.ts
- src/main/resources/public/ts/services/attachment.service.ts
- src/main/resources/public/ts/utils/safeApply.ts
- src/test/java/net/atos/entng/support/services/AttachmentServiceSqlImplTest.java
- src/test/java/net/atos/entng/support/test/SimpleTest.java
- tsconfig.json
- Dev Back new endpoint
- Dev Front service + call endpoint
- fichier scss
- test unitaire
> feat(attachment): #CO-430 add attachment option to delete

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/enums/BugTracker.java
- src/main/java/net/atos/entng/support/helpers/DateHelper.java
- src/main/java/net/atos/entng/support/services/TicketServiceSql.java
- src/main/java/net/atos/entng/support/services/impl/EscalationServicePivotImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/resources/public/template/view-ticket.html
Affiche dans l'assistance ENT l'id et le statut JIRA du ticket escaladé
> feat(support): #EV-300 display jira ticket id for escalated tickets

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/enums/BugTracker.java
- src/main/java/net/atos/entng/support/enums/TicketStatusJira.java
- src/main/java/net/atos/entng/support/helpers/DateHelper.java
- src/main/java/net/atos/entng/support/services/impl/EscalationServicePivotImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/resources/public/template/view-ticket.html
Envoie un message de notification dans l'Assistance ENT pour alerter du changement de statut du ticket dans JIRA
> feat(support): #EV-301 notify jira status change in comments

- .github/workflows/dev-check-repository.yml
- docker-compose.yml
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/enums/BugTracker.java
- src/test/java/net/atos/entng/support/enums/BugTrackerTest.java
Correction de l'escalade d'un ticket vers Redmine ou l'on rencontrait une erreur de NumberFormatException
MO-145 : https://jira.support-ent.fr/browse/MO-145
> fix(support): #MO-145 fix escalation to redmine

- src/main/java/net/atos/entng/support/controllers/TicketController.java
Add a connection security for the recovery of a profile.
Display a user's profile from the module
[CO-1666](https://jira.support-ent.fr/browse/CO-1666)
> fix(security): #CO-1665 add security TicketConroller

- src/main/java/net/atos/entng/support/controllers/TicketController.java
Fix typing problem. With jira we got String with IWS we got long.
Update an iws ticket
[CO-1684](https://jira.support-ent.fr/browse/CO-1684)
> fix(update): #CO-1684 fix typing during status change notifications

- src/main/resources/public/css/additional.css
Setting lightbox's height and hiding useless text input under uploading file button
Tests on autocomplete search input for attachments files to check whether the height is remaining good
[#CO-1729] (https://jira.support-ent.fr/browse/CO-1729)
> fix(css):#CO-1729 lightbox import attachments

- src/main/resources/public/template/edit-ticket.html
- Select input for school name no longer pass through the ticket modification date label
- Margin left on ticket status label, ticket creation date label and ticket modification date label
Check if the select input for school name don't pass through the ticket modification date label
[CO-810](https://jira.support-ent.fr/browse/CO-810)
> fix(edit-ticket): #CO-810 responsive for edit-ticket page

- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/resources/public/ts/controllers/controller.ts
Now when you create a ticket, it's automatically on the top of the list and you don't need to refresh the page to see it.
Some super admins are not linked to only one structure, so now they can see tickets of all their structures and not only the first one.
Create a new ticket and check if it's on the top of the list
[CO-1765](https://jira.support-ent.fr/browse/CO-1765)
> fix(display-ticket): #CO-1765 new ticket on top of the list

- src/main/resources/public/template/add-attachment-lightbox.html
- src/main/resources/public/ts/controllers/controller.ts
You can now import more than one attachment from your PC instead of using shared documents from "espace documentaire"
- Import an attachment from your PC and add it to the ticket
- Repeat as many time as you want attachments
- Check that you have all the attachments you added
[CO-1771](https://jira.support-ent.fr/browse/CO-1771)
> fix(attachment): #CO-1771 import 2 local attachments

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
Add i18n key for "file.too.large.limit"
- Try to import an attachment > 50mb and check if a pop-up with an i18n translated key spawn
[CO-1744](https://jira.support-ent.fr/browse/CO-1744)
> fix(message): #CO-1744 add i18n key for file.too.large.limit

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/list-tickets.html
When you are on list ticket, you can now see the structure of the person who created the ticket
- Check that the correct structure appears next to each person
[CO-1759](https://jira.support-ent.fr/browse/CO-1759)
> feat(structure-column): #CO-1759 add structure column in list ticket

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/create-ticket.html
Add "Select a category" option on select category when you create a ticket.
It's selected by default, and the create button is disabled if you select it has a category.
- Chose the option "Select a category" option and check if the create ticket button is disable.
- Change the category and check if the button is enable.
[CO-1760](https://jira.support-ent.fr/browse/CO-1760)
> feat(create-ticket): #CO-1760 add default select option

- src/main/java/net/atos/entng/support/Support.java
- src/main/java/net/atos/entng/support/controllers/ConfigController.java
Add an API endpoint to access the config of the module.
This route is only allowed for admins.
- Try /config API endpoint and check if the config of the module is correctly returned
[CO-1772](https://jira.support-ent.fr/browse/CO-1772)
> feat(config): #CO-1772 add route /config

- src/main/resources/public/template/edit-ticket.html
In edit ticket change of directive from "attachment" to "media-library"
- Edit a ticket and click on "add an attachment"
- Check if the pop-up appears correctly
- Add attachment and check if it's correctly added
[CO-1761](https://jira.support-ent.fr/browse/CO-1761)
> feat(edit-ticket): #CO-1761 change attachment directive

- build-noDocker.sh
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/filters/OwnerOrLocalAdmin.java
- src/main/resources/jsonschema/ticketUpdate.json
- Adding SecuredAction on endpoints with exposed resources
- Enriching the OwnerOrLocalAdmin filter with handling resource ids from request body
Note :
- In order to be able to build locally I added a `build-noDocker.sh` script
- Reproducing an illegal attempt to access and update the resources that used to be exposed
- Verifying you get rejected.
This fixes the three IDOR vulnerabilities on Support module:
https://opendigitaleducation.atlassian.net/browse/WB-1549
https://opendigitaleducation.atlassian.net/browse/WB-1555
https://opendigitaleducation.atlassian.net/browse/WB-1556
> Bug IDOR security vulnerability on Support module

- src/main/resources/public/template/create-ticket.html
- src/main/resources/public/ts/controllers/controller.ts
When you create a ticket if subject or description field is blank the create button is disable.
[CO-1760](https://jira.support-ent.fr/browse/CO-1760)
> feat(create-ticket): #CO-1760 disable create button when subject or description is blank

- src/main/resources/public/ts/controllers/controller.ts
When a local admin responds to a ticket, it will change the status to "waiting response from user".
When a user responds to a ticket that has the status "waiting response from user" will change the status to "open".
- As an admin, update a ticket that has the status "open" and check if the status change to "waiting response from user"
- As a user, update a ticket that has the status "waiting response from user" and check if the status change to "open"
[CO-1754](https://jira.support-ent.fr/browse/CO-1754)
> feat(change-status): #CO-1754 change ticket status after response

- src/main/resources/public/template/create-ticket.html
Disable save and escalate button if the form for creating a ticket is not completely filled
Go to the create ticket page and check if create and escalate button is disable if the form is not complete
[CO-1760](https://jira.support-ent.fr/browse/CO-1760)
> feat(create-ticket): #CO-1760 disable save and escalate button if form is not fully completed

- src/main/java/net/atos/entng/support/export/CSVExport.java
- src/main/java/net/atos/entng/support/export/TicketsCSVExport.java
When export tickets, ticket number is now translate to status name
Export tickets and check if in column "status" there is status name
[CO-1757](https://jira.support-ent.fr/browse/CO-1757)
> feat(export-csv): #CO-1757 translate ticket status number

- src/main/resources/public/template/list-tickets.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/models/model.ts
- src/main/resources/public/ts/models/ticket.model.ts
Checkbox that select all tickets
[CO-1756](https://jira.support-ent.fr/browse/CO-1756)
> feat(select-all): #CO-1756 select all ticket checkbox

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/export/CSVExport.java
- src/main/java/net/atos/entng/support/export/TicketsCSVExport.java
- src/main/java/net/atos/entng/support/helpers/DateHelper.java
- src/main/java/net/atos/entng/support/services/TicketService.java
- src/main/java/net/atos/entng/support/services/TicketServiceNeo4j.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceNeo4jImpl.java
- src/main/resources/public/template/list-tickets.html
- src/main/resources/public/ts/controllers/controller.ts
Change date format ("dd/MM/yyyy - HH:mm"), translate school id to school name and management of old category names
- Select tickets and export them.
- Check if the csv file has good date format ("dd/MM/yyyy - HH:mm") and if school have a name and not an id
[CO-1757](https://jira.support-ent.fr/browse/CO-1757)
> feat(formatting-data): #CO-1757 change date format and translate school name

- src/main/java/net/atos/entng/support/Support.java
- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/FakeRight.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/services/TicketService.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceNeo4jImpl.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/enum/workflow.enum.ts
- src/main/resources/public/ts/models/schoolWorkflow.model.ts
- src/main/resources/public/ts/services/ticket.service.ts
You can now configure if when a local admin open a ticket, it will automatically change status to open or not
[API DOC](https://confluence.support-ent.fr/x/Go4BB) : /check/user/{id}/workflow/{workflow}/structure/{structureId}/auto/open
Give the workflow right "support.ticket.auto.open" to a structure.
- With a local admin of a structure who has the workflow right, open a ticket of the structure with status "new", check if it change to "open"
- With a local admin of a structure who doesn't have the workflow right, open a ticket of the structure with status "new", check if it stay at "new"
[CO-1777](https://jira.support-ent.fr/browse/CO-1777)
> feat(auto-open-ticket): #CO-1777 add possibility to configure change status when open ticket

- src/main/resources/public/ts/controllers/controller.ts
As an adml when you click on edit ticket button, it will not change the status from new to open
[CO-1782](https://jira.support-ent.fr/browse/CO-1782)
> fix(select-status): #CO-1782 remove when you click on edit ticket it will change status to open

- src/main/resources/public/ts/controllers/controller.ts
As an adml when you click on edit ticket button, it will no longer change the status from open to waiting
As an ADML, edit a ticket with OPEN status and check that the status is not automatically changed to WAITING
[CO-1783](https://jira.support-ent.fr/browse/CO-1783)
> fix(select-status): #CO-1783 remove auto change status from open to waiting

- src/main/resources/public/ts/controllers/controller.ts
If cancel when you are on edit ticket page, the informations are now the ticket's informations before you clicked on the update button
Go to update page ticket, modify informations but click on cancel and check if the informations are the originals
[CO-1786](https://jira.support-ent.fr/browse/CO-1786)
> fix(cancel-uptade): #CO-1786 original ticket info when cancel update ticket

- src/main/resources/public/ts/controllers/controller.ts
Create and escalate is now executed before gopage
When you create a ticket and click on "create and escalate" button, check if the ticket is correctly created and executed
[CO-1787](https://jira.support-ent.fr/browse/CO-1787)
> fix(create-and-escalate): #CO-1787 create and escalate execute before gopage

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/services/impl/EscalationServicePivotImpl.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/models/model.ts
If you try to escalate a ticket that has a file too large for Jira, it will fail the escalation and send an http 413 error (Payload Too Large).
- Escalate a ticket with a file bigger than 10mb and check if it display the error and fail the escalation
[CO-1748](https://jira.support-ent.fr/browse/CO-1748)
> fix(file-too-large): #CO-1748 send http error 413

- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/view-src/support.html
Fix the "Assistance ENT" button that permits to return to the main page of support
Click on the button "Assistance ENT" and check if you correctly return on the main page
[CO-1790](https://jira.support-ent.fr/browse/CO-1790)
> fix(home-button): #CO-1790 fix go to main page button

- src/main/resources/public/ts/controllers/controller.ts
Fix the "Assistance ENT" button that permits to return to the main page of support
- Click on the button "Assistance ENT" and check if you correctly return on the main page
[CO-1790](https://jira.support-ent.fr/browse/CO-1790)
> fix(home-button): #CO-1790 reset ticket when back to main page

- src/main/resources/public/ts/models/model.ts
When I uncheck all the status filters, there are no ticket displayed now
- Uncheck all the status filters and check if there are no ticket displayed
[CO-1789](https://jira.support-ent.fr/browse/CO-1789)
> fix(filter): #CO-1789 display no tickets if all filters are disabled

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/enums/Error.java
- src/main/java/net/atos/entng/support/services/TicketService.java
- src/main/java/net/atos/entng/support/services/TicketServiceSql.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceNeo4jImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/list-tickets.html
- src/main/resources/public/ts/models/model.ts
- src/main/resources/public/ts/services/ticket.service.ts
You can now sort tickets by structure name by clicking on "structure du demandeur"
- Click on "structure du demandeur" on check if the tickets are correctly sorted by structure name
[CO-1793](https://jira.support-ent.fr/browse/CO-1793)
> feat(sort-structure): #CO-1793 add possibility to sort tickets by structure name

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/export/TicketExportWorker.java
- src/main/java/net/atos/entng/support/export/TicketsCSVExport.java
- src/main/java/net/atos/entng/support/helpers/CSVHelper.java
- src/main/java/net/atos/entng/support/helpers/IModelHelper.java
- src/main/java/net/atos/entng/support/helpers/UserInfosHelper.java
- src/main/java/net/atos/entng/support/model/TicketModel.java
- src/main/java/net/atos/entng/support/services/TicketService.java
- src/main/java/net/atos/entng/support/services/TicketServiceSql.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/test/java/net/atos/entng/support/services/TicketServiceSqlImplTest.java
When you export a ticket, it will now correctly translate category addresses to their names
- Export tickets and check if categories are correctly translate
[CO-1795](https://jira.support-ent.fr/browse/CO-1795)
> fix(export): #CO-1795 translate correctly categories

- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/services/TicketServiceSql.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
You can now see the substructures of a master structure when you select it
- Select a master structure and check if you can see the substructures
[CO-1796](https://jira.support-ent.fr/browse/CO-1796)
> feat(substructures): #CO-1796 add possiblity to view substructures of  a master structure

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/helpers/UserInfosHelper.java
Because of the new way of translating category's address to their names, the export with the worker wasn't working.
So now, when you use the worker, it will now correctly export the CSV
- Export tickets by using the worker and check if the CSV is correctly generated
[CO-1795](https://jira.support-ent.fr/browse/CO-1795)
> fix(worker): #CO-1795 translate correctly when user worker

- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/export/TicketExportWorker.java
- src/main/java/net/atos/entng/support/services/TicketService.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceNeo4jImpl.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/ts/controllers/controller.ts
When you export all the structures with the worker, it will now correctly also export the substructures
Export tickets and check if the substructure's tickets are exported
[CO-1795](https://jira.support-ent.fr/browse/CO-1795)
> fix(worker): #CO-1795 add substructures to csv when export all

- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
You can now sort tickets by structure name by clicking on "structure du demandeur"
It now works for postgresql 9
- Click on "structure du demandeur" on check if the tickets are correctly sorted by structure name
[CO-1793](https://jira.support-ent.fr/browse/CO-1793)
> feat(sort-structure): #CO-1793 adapt for postgresql 9

- src/main/java/net/atos/entng/support/controllers/TicketController.java
When sorted by structure, this now takes account of sub-structures
Sort by structures name and check if it's correctly sorted 
[CO-1793](https://jira.support-ent.fr/browse/CO-1793)
> feat(sort-structure): #CO-1793 add substructures to sort

- src/main/java/net/atos/entng/support/services/ServiceFactory.java
The escalationActivated variable is never initialized, which blocks ticket escalation.
Escalate a ticket, add a comment, add an attachment.
https://jira.support-ent.fr/browse/CO-1812
> fix: #CO-1812 fix npe when when escalating a ticket

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/enums/Error.java
- src/main/java/net/atos/entng/support/services/ServiceFactory.java
- src/main/java/net/atos/entng/support/services/TicketServiceSql.java
- src/main/java/net/atos/entng/support/services/UserService.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/java/net/atos/entng/support/services/impl/UserServiceDirectoryImpl.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/list-tickets.html
Ajout du tri par profile
Sur l'accueil de support, cliquer sur la colone "profile". Le tri s'effectue (dans un sens et dans l'autre).
[Jira - CO-1803](https://jira.support-ent.fr/browse/CO-1803)
> feat(list-ticket): #CO-1803 order list tickets by profile

- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/models/model.ts
Réouvre un ticket fermé lorsqu'on lui ajoute un nouveau commentaire.
- Fermer un ticket Ouvert (avec un commentaire si souhaité) -> le ticket passe à Fermé
- Commenter ce même ticket fermé -> le ticket passe à Ouvert.
[Jira - CO-1802](https://jira.support-ent.fr/browse/CO-1802)
> feat(comment-ticket): #CO-1802 reopen ticket on a new comment

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/FakeRight.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/enum/workflow.enum.ts
When a ticket is "closed" and someone writes a comment, a specific right must be assigned for the ticket to re-open and get the status "open"
With an account that does not have the correct rights, write a comment in a "closed" ticket, it will not reopen.
With the right, do the same manipulation, the ticket opens
[https://jira.support-ent.fr/browse/CO-1802](https://jira.support-ent.fr/browse/CO-1802)
> feat(comment-ticket): #CO-1802 rights for reopen ticket on a new comment

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/enum/workflow.enum.ts
I changed the name of the right because the right no longer depends on comments.
Also, instead of changing the status only if the user leaves a comment, the status changes to "open" as soon as the ticket is modified
**Before all, check if the user have the good right**
* Create a ticket
* Edit this ticket and close it
* Re-edit the ticket, the ticket status has changed to open
[https://jira.support-ent.fr/browse/CO-1802](https://jira.support-ent.fr/browse/CO-1802)
> #CO-1802: Update status when edit ticket

- src/main/java/net/atos/entng/support/constants/Ticket.java
- src/main/java/net/atos/entng/support/controllers/ConfigController.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/models/nbTicketsPerPage.model.ts
- src/main/resources/public/ts/services/ticket.service.ts
Get the number of tickets displayed per pages from config
- Have less than 25 tickets and after create a new ticket, check if there is no second page
[CO-1799](https://jira.support-ent.fr/browse/CO-1799)
> fix(page): #CO-1799 remove blank page after create a new ticket

- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/resources/public/ts/controllers/controller.ts
When all the status filters check-boxes are checked, it will now automatically check the "all" checkbox
The filters now work if we are an ADML.
- Uncheck the "all" checkbox and check all the status filters and watch if the "all" checkbox is checked
- Log in Super Admin account and check if filters works
- Log in Local Admin account and check if filters works
- Log in Normal account and check if filters works
[CO-1789](https://jira.support-ent.fr/browse/CO-1789)
> fix(status): #CO-1789 check the all status checkbox if all status filters are true

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/models/model.ts
Currently, if you created a ticket and it returned a bad request, you could no longer create a ticket.
Now, it returns an error, but you can still recreate a ticket.
- Custom route POST `/support/ticket` to send a response 400 and try to create two tickets
[https://jira.support-ent.fr/browse/CO-1817](https://jira.support-ent.fr/browse/CO-1817)
> feature(pictures): #CO-1817 check bad request when create ticket

- src/main/resources/i18n/fr.json
> chore(ent77)SUPPORT-1483 rename 'aide et support' into 'support ENT'

- .github/workflows/dev-check-repository.yml
- src/main/java/net/atos/entng/support/constants/JiraTicket.java
- src/main/java/net/atos/entng/support/controllers/TicketController.java
- src/main/java/net/atos/entng/support/enums/Actions.java
- src/main/java/net/atos/entng/support/enums/I18nKeys.java
- src/main/java/net/atos/entng/support/export/TicketExportWorker.java
- src/main/java/net/atos/entng/support/helpers/I18nHelper.java
- src/main/java/net/atos/entng/support/helpers/TransactionHelper.java
- src/main/java/net/atos/entng/support/model/TransactionElement.java
- src/main/java/net/atos/entng/support/services/ServiceFactory.java
- src/main/java/net/atos/entng/support/services/TicketService.java
- src/main/java/net/atos/entng/support/services/TicketServiceSql.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceNeo4jImpl.java
- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/resources/public/template/list-tickets.html
- src/main/resources/sql/026-add-category-label-column.sql
Add a column in tickets table. This column now store the same categoryLabel as in front, allowing to sort our data as expected in front.
We also added a function allowing to fill old row of the table.
CO-1859 : https://jira.support-ent.fr/browse/CO-1859
> fix(category): [#CO-1859] add category_label column in database

- Jenkinsfile
- build.sh
- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
- src/main/resources/public/template/edit-ticket.html
- src/main/resources/public/ts/controllers/controller.ts
Once escalated, tickets should evolve through comments, not by modifying the description.
* prevent on the frontend and backend sides.
https://edifice-community.atlassian.net/browse/COCO-4341
> feat: COCO-4341, prevent updating description of escalated tickets

- src/main/java/net/atos/entng/support/services/impl/TicketServiceSqlImpl.java
Ajouter aux ADMC le même comportement que pour les ADML. Lister tous les tickets enfants d'une structure parent et des enfants.
[#COCO-4563](https://edifice-community.atlassian.net/browse/COCO-4563)
> fix(support): #COCO-4563, ADMC list tickets for all structures

- src/main/java/net/atos/entng/support/services/impl/EscalationServicePivotImpl.java
- src/main/java/net/atos/entng/support/services/impl/EscalationServiceRedmineImpl.java
- src/main/java/net/atos/entng/support/services/impl/EscalationServiceZendeskImpl.java
Changement des paramètres des push notification pour les tickets escaladés afin d'inclure les numéros des tickets dans le message.
https://edifice-community.atlassian.net/browse/COCO-4729
> Fix coco 4729 ticket number not appear in push notif
